# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Powertmux < Formula
  desc "Drop-in tmux.conf with a styled status bar, window tabs, and sane defaults"
  homepage "https://github.com/napalm255/powertmux"
  version "1.1.0"
  license "Unlicense"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.0/powertmux_1.1.0_darwin_amd64.tar.gz"
      sha256 "e5926b8c1c4a0b2a06bf9470c332e9e789755154aea52621bfa45ba651086e39"

      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.0/powertmux_1.1.0_darwin_arm64.tar.gz"
      sha256 "6f920fe36dee0aa9ba4d03a87bd19668a24760670bbd2bdcc2047467465ee8f3"

      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.0/powertmux_1.1.0_linux_amd64.tar.gz"
      sha256 "73fbf3b5e7b5513756b515f0ae1375c4c3bb325deed9ec93afc40f74fcab483b"
      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.0/powertmux_1.1.0_linux_arm64.tar.gz"
      sha256 "fa70877c93382ac9bb41bbc85003d170b90ebcc6939f886b23dcdf1704162984"
      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
  end

  def caveats
    <<~EOS
      Run `powertmux install` to install tmux.conf to the standard XDG path
      ($XDG_CONFIG_HOME/tmux/tmux.conf, falling back to
      ~/.config/tmux/tmux.conf) — this is the recommended way to use powertmux.

      tmux.conf was also installed read-only to:
        #{opt_pkgshare}/tmux.conf

      To symlink that copy in manually instead:
        mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/tmux"
        ln -sf "#{opt_pkgshare}/tmux.conf" "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
    EOS
  end

  test do
    system bin/"powertmux", "--version"

    tmux = formula_opt_bin("tmux")/"tmux"
    system tmux, "-f", pkgshare/"tmux.conf", "new-session", "-d", "-s", "powertmux_test"
    system tmux, "kill-session", "-t", "powertmux_test"
  end
end
