# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Powertmux < Formula
  desc "Drop-in tmux.conf with a styled status bar, window tabs, and sane defaults"
  homepage "https://github.com/napalm255/powertmux"
  version "1.1.2"
  license "Unlicense"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.2/powertmux_1.1.2_darwin_amd64.tar.gz"
      sha256 "71893b735577c6af1d2f37238bfb65802368daaff73a5c7b39f70afe523d835c"

      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.2/powertmux_1.1.2_darwin_arm64.tar.gz"
      sha256 "8d0de79ba3ad1141461ee3094a25102d2cffa228414de6c7bdf4b324486643a6"

      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.2/powertmux_1.1.2_linux_amd64.tar.gz"
      sha256 "f01e1d112ff65d987bfc69815ca80cf05316fbf747b1da56edc70d2fe5654692"
      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.2/powertmux_1.1.2_linux_arm64.tar.gz"
      sha256 "bcbcad28f6a34654b16d5560e90024860540188c47812b5c6092b9887685db6c"
      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
  end

  def caveats
    <<~EOS
      Run `powertmux install` to install tmux.conf to the standard XDG path
      ($XDG_CONFIG_HOME/tmux/tmux.conf, falling back to
      ~/.config/tmux/tmux.conf) — this is the recommended way to use powertmux.

      tmux.conf was also installed read-only to:
        #{opt_pkgshare}/tmux.conf

      To symlink that copy in manually instead:
        mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/tmux"
        ln -sf "#{opt_pkgshare}/tmux.conf" "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
    EOS
  end

  test do
    system bin/"powertmux", "--version"

    tmux = formula_opt_bin("tmux")/"tmux"
    system tmux, "-f", pkgshare/"tmux.conf", "new-session", "-d", "-s", "powertmux_test"
    system tmux, "kill-session", "-t", "powertmux_test"
  end
end
