# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Powertmux < Formula
  desc "Drop-in tmux.conf with a styled status bar, window tabs, and sane defaults"
  homepage "https://github.com/napalm255/powertmux"
  version "1.1.1"
  license "Unlicense"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.1/powertmux_1.1.1_darwin_amd64.tar.gz"
      sha256 "9845ef0c88996fdf4aca76432122f32816581b87df7b7cec07f9ec165def01c7"

      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.1/powertmux_1.1.1_darwin_arm64.tar.gz"
      sha256 "f6c69231afc9f1b861100e21d88a56ce3df6f28777932b4c02fee626c9cb1a9a"

      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.1/powertmux_1.1.1_linux_amd64.tar.gz"
      sha256 "8af52a093b263465effbbd59f690890f4e6933d83a6938eff32cfaa2ca0a1a35"
      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/napalm255/powertmux/releases/download/v1.1.1/powertmux_1.1.1_linux_arm64.tar.gz"
      sha256 "4208aacde36da4d93f8c2066acd6100dc63a1f1811ad7e8b79332b468a5651ba"
      define_method(:install) do
        bin.install "powertmux"
        pkgshare.install "tmux.conf"
      end
    end
  end

  def caveats
    <<~EOS
      Run `powertmux install` to install tmux.conf to the standard XDG path
      ($XDG_CONFIG_HOME/tmux/tmux.conf, falling back to
      ~/.config/tmux/tmux.conf) — this is the recommended way to use powertmux.

      tmux.conf was also installed read-only to:
        #{opt_pkgshare}/tmux.conf

      To symlink that copy in manually instead:
        mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/tmux"
        ln -sf "#{opt_pkgshare}/tmux.conf" "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
    EOS
  end

  test do
    system bin/"powertmux", "--version"

    tmux = formula_opt_bin("tmux")/"tmux"
    system tmux, "-f", pkgshare/"tmux.conf", "new-session", "-d", "-s", "powertmux_test"
    system tmux, "kill-session", "-t", "powertmux_test"
  end
end
